export const handyCat = [
    {"id": 1, "category": "Electrical"},
    {"id": 2, "category": "Plumber"},
    {"id": 3, "category": "Carpenter"},
    {"id": 4, "category": "Painter"},
    {"id": 5, "category": "Tiler"},
    {"id": 6, "category": "Roofing"},
    {"id": 7, "category": "Flooring"},
    {"id": 8, "category": "Drywall Installation"},
    {"id": 9, "category": "Pressure Washing"},
    {"id": 10, "category": "Home Renovation"},
    {"id": 11, "category": "Furniture Assembly"},
    {"id": 12, "category": "Window Repair"},
    {"id": 13, "category": "Fence Repair"},
    {"id": 14, "category": "Door Installation"},
    {"id": 15, "category": "Lock Installation"},
    {"id": 16, "category": "Siding Installation"},
    {"id": 17, "category": "Gutter Cleaning"},
    {"id": 18, "category": "Landscaping"},
    {"id": 19, "category": "Tree Removal"},
    {"id": 20, "category": "Pest Control"},
    {"id": 21, "category": "Garage Organization"},
    {"id": 22, "category": "Tile Grouting"},
    {"id": 23, "category": "Cabinet Installation"},
    {"id": 24, "category": "Countertop Installation"},
    {"id": 25, "category": "Appliance Installation"},
    {"id": 26, "category": "Smart Home Installation"},
    {"id": 27, "category": "Plumbing Fixtures Installation"},
    {"id": 28, "category": "Bathroom Remodeling"},
    {"id": 29, "category": "Kitchen Remodeling"},
    {"id": 30, "category": "HVAC Installation"},
    {"id": 31, "category": "HVAC Repair"},
    {"id": 32, "category": "Basement Waterproofing"},
    {"id": 33, "category": "Handyman for Seniors"},
    {"id": 34, "category": "Home Inspection"},
    {"id": 35, "category": "Deck Repair"},
    {"id": 36, "category": "Deck Building"},
    {"id": 37, "category": "Flooring Installation"},
    {"id": 38, "category": "Window Installation"},
    {"id": 39, "category": "Electrical Repairs"},
    {"id": 40, "category": "Plumbing Repairs"},
    {"id": 41, "category": "Furniture Repair"},
    {"id": 42, "category": "Lighting Installation"},
    {"id": 43, "category": "Carpet Installation"},
    {"id": 44, "category": "Carpet Cleaning"},
    {"id": 45, "category": "Appliance Repair"},
    {"id": 46, "category": "Painting Touch-ups"},
    {"id": 47, "category": "Wallpaper Removal"},
    {"id": 48, "category": "Wallpaper Installation"},
    {"id": 49, "category": "Ceiling Fan Installation"},
    {"id": 50, "category": "Fence Installation"},
    {"id": 51, "category": "Door Repair"},
    {"id": 52, "category": "Driveway Repair"},
    {"id": 53, "category": "Insulation Installation"},
    {"id": 54, "category": "Water Heater Repair"},
    {"id": 55, "category": "Water Heater Installation"},
    {"id": 56, "category": "Tile Repair"},
    {"id": 57, "category": "Plumbing Leak Repair"},
    {"id": 58, "category": "Home Theater Installation"},
    {"id": 59, "category": "Wall Mounting TVs"},
    {"id": 60, "category": "Refrigerator Installation"},
    {"id": 61, "category": "Dishwasher Installation"},
    {"id": 62, "category": "Air Conditioning Installation"},
    {"id": 63, "category": "Air Conditioning Repair"},
    {"id": 64, "category": "Gutter Installation"},
    {"id": 65, "category": "Water Softener Installation"},
    {"id": 66, "category": "Sprinkler System Installation"},
    {"id": 67, "category": "Sprinkler System Repair"},
    {"id": 68, "category": "Kitchen Sink Repair"},
    {"id": 69, "category": "Bathroom Sink Repair"},
    {"id": 70, "category": "Shower Installation"},
    {"id": 71, "category": "Bathtub Installation"},
    {"id": 72, "category": "Dryer Vent Cleaning"},
    {"id": 73, "category": "Home Automation Services"},
    {"id": 74, "category": "Air Duct Cleaning"},
    {"id": 75, "category": "Attic Insulation"},
    {"id": 76, "category": "Mold Remediation"},
    {"id": 77, "category": "Home Security Installation"},
    {"id": 78, "category": "Storm Door Installation"},
    {"id": 79, "category": "Concrete Repair"},
    {"id": 80, "category": "Masonry Services"},
    {"id": 81, "category": "Makeup Artist"},
    {"id": 82, "category": "Hair Stylist"},
    {"id": 83, "category": "Nail Technician"},
    {"id": 84, "category": "Eyebrow Threading"},
    {"id": 85, "category": "Lash Extensions"},
    {"id": 86, "category": "Facials"},
    {"id": 87, "category": "Bridal Makeup"},
    {"id": 88, "category": "Massage Therapist"},
    {"id": 89, "category": "Skin Care Specialist"},
    {"id": 90, "category": "Personal Shopper"},
    {"id": 91, "category": "Personal Trainer"},
    {"id": 92, "category": "Yoga Instructor"},
    {"id": 93, "category": "Dietitian"},
    {"id": 94, "category": "Hair Colorist"},
    {"id": 95, "category": "Waxing Specialist"},
    {"id": 96, "category": "Tattoo Artist"},
    {"id": 97, "category": "Piercing Specialist"},
    {"id": 98, "category": "Fitness Coach"},
    {"id": 99, "category": "Spa Services"},
    {"id": 100, "category": "Cosmetic Dentist"},
    {"id": 101, "category": "Auto Mechanic"},
    {"id": 102, "category": "Car Detailing"},
    {"id": 103, "category": "Car Maintenance"},
    {"id": 104, "category": "Transmission Repair"},
    {"id": 105, "category": "Engine Diagnostics"},
    {"id": 106, "category": "Battery Replacement"},
    {"id": 107, "category": "Brake Service"},
    {"id": 108, "category": "Tire Services"},
    {"id": 109, "category": "Car Paint Repair"},
    {"id": 110, "category": "AC Repair for Cars"},
    {"id": 111, "category": "Auto Glass Repair"},
    {"id": 112, "category": "Electric Vehicle Services"},
    {"id": 113, "category": "Drone Services"},
    {"id": 114, "category": "IT Support"},
    {"id": 115, "category": "Web Development"},
    {"id": 116, "category": "Mobile App Development"},
    {"id": 117, "category": "Network Setup"},
    {"id": 118, "category": "Cloud Computing Services"},
    {"id": 119, "category": "Cybersecurity Services"},
    {"id": 120, "category": "Smartphone Repair"},
    {"id": 121, "category": "Laptop Repair"},
    {"id": 122, "category": "Home Automation Installation"},
    {"id": 123, "category": "VR/AR Services"},
    {"id": 124, "category": "Artificial Intelligence Consulting"},
    {"id": 125, "category": "Game Development"},
    {"id": 126, "category": "3D Printing Services"},
    {"id": 127, "category": "Website Design"},
    {"id": 128, "category": "SEO Services"},
    {"id": 129, "category": "E-commerce Development"},
    {"id": 130, "category": "Blockchain Development"},
    {"id": 131, "category": "Plumber"},
    {"id": 132, "category": "Electrician"},
    {"id": 133, "category": "Roofer"},
    {"id": 134, "category": "Builder"},
    {"id": 135, "category": "Gardener"},
    {"id": 136, "category": "Painter"},
    {"id": 137, "category": "Locksmith"},
    {"id": 138, "category": "Bathrooms"},
    {"id": 139, "category": "Tiler"},
    {"id": 140, "category": "Central Heating"},
    {"id": 141, "category": "Boiler Repair"},
    {"id": 142, "category": "Air Purifier Installation"},
    {"id": 143, "category": "Home Theatre System Installation"},
    {"id": 144, "category": "Tile Sealing"},
    {"id": 145, "category": "Pressure Cleaning"},
    {"id": 146, "category": "Deck Staining"},
    {"id": 147, "category": "Staircase Installation"},
    {"id": 148, "category": "Gutter Guards Installation"},
    {"id": 149, "category": "Window Tinting"},
    {"id": 150, "category": "Curtain Installation"},
    {"id": 151, "category": "Interior Design"},
    {"id": 152, "category": "Reupholstery Services"},
    {"id": 153, "category": "Roof Inspection"},
    {"id": 154, "category": "Concrete Cutting"},
    {"id": 155, "category": "Wallpapering Services"},
    {"id": 156, "category": "Property Maintenance"},
    {"id": 157, "category": "Appliance Repair Services"},
    {"id": 158, "category": "Garden Maintenance"},
    {"id": 159, "category": "Landscape Design"},
    {"id": 160, "category": "CCTV Installation"},
    {"id": 161, "category": "Fire Alarm Installation"},
    {"id": 162, "category": "Electric Fencing Installation"},
    {"id": 163, "category": "Plumbing Leak Detection"},
    {"id": 164, "category": "Thermal Insulation Installation"},
    {"id": 165, "category": "Pond Cleaning"},
    {"id": 166, "category": "Tree Pruning"},
    {"id": 167, "category": "Stump Removal"},
    {"id": 168, "category": "Pool Maintenance"},
    {"id": 169, "category": "Pool Installation"},
    {"id": 170, "category": "Fireplace Installation"},
    {"id": 171, "category": "Chimney Sweeping"},
    {"id": 172, "category": "Hot Tub Installation"},
    {"id": 173, "category": "Soundproofing Services"},
    {"id": 174, "category": "Pressure Test for Pipes"},
    {"id": 175, "category": "Roof Repair"},
    {"id": 176, "category": "Gas Line Installation"},
    {"id": 177, "category": "Water Line Installation"},
    {"id": 178, "category": "Home Staging"},
    {"id": 179, "category": "Solar Panel Installation"},
    {"id": 180, "category": "Smart Thermostat Installation"},
    {"id": 181, "category": "Smart Security System Installation"},
    {"id": 182, "category": "Electric Car Charging Station Installation"},
    {"id": 183, "category": "Green Building Construction"},
    {"id": 184, "category": "Luxury Home Design"},
    {"id": 185, "category": "Waste Disposal Services"},
    {"id": 186, "category": "Moving Services"},
    {"id": 187, "category": "Furniture Moving"},
    {"id": 188, "category": "Cleaning Services"},
    {"id": 189, "category": "Clutter Removal"},
    {"id": 190, "category": "Junk Removal"},
    {"id": 191, "category": "Event Setup"},
    {"id": 192, "category": "Wedding Planning"},
    {"id": 193, "category": "Party Planning"},
    {"id": 194, "category": "Catering Services"},
    {"id": 195, "category": "Cleaning Crew for Events"},
    {"id": 196, "category": "Limo Services"},
    {"id": 197, "category": "Bartender Services"},
    {"id": 198, "category": "DJ Services"},
    {"id": 199, "category": "Photographer Services"},
    {"id": 200, "category": "Videographer Services"}
  ]
  